### ISSUE TITLE
freshly installed architecture api prevents MC from starting

### ISSUE THREAD

**Issue by Harlekin13** [architectury/architectury#100]
Okay after installing architecture MC won't start anymore.
I only installed it, because FTB library wants it to function.
Which i only installed because JEI wants it to access all functions.

I have no idea why.
here's the log: https://paste.ee/p/WcCDN

**Comment by shedaniel** [comment]
Did you include the wrong log? The log you sent is from three days ago and doesn't include the crash.

**Comment by Harlekin13** [comment]
damn... one moment
was the wrong one, was the latest named with a date.

okay that should be the right one now: https://paste.ee/p/FeWkB

restarted it again, now it started, but sadly ftb library still won't work or at least JEI doesn't recognize it... (which is probably not your problem, if it isn't because architecture won't even be loaded)

but it could be this one too... the above is latest.log this is debug.log: https://paste.ee/p/qpBQe

**Comment by MaxNeedsSnacks** [comment]
That crash isn't related since it just means you didn't have Architectury installed at the time.

You're using a new version of JEI with an old version of FTB Library (which was called FTB GUI Library at the time), see this comment for reference: https://github.com/mezz/JustEnoughItems/issues/2355#issuecomment-842630298
