### ISSUE TITLE
Server crashes sometimes with "Where is architectury?"

### ISSUE THREAD

**Issue by RagingLightning** [architectury/architectury#135]
Hi,

I'm working on a custom modpack and thiss mod is currently a sore thumb of mine...
Most of the time, everything works perfectly, but every so often (once in 20 server starts or something like that), It just crashes, throwing an "IllegalStateException: Where is architectury?"

[crash report](https://pastebin.com/yeE0HCpg)

I've tried to have a look at the code to figure out, what goes wrong, but I was unable to find anything.

I'd love a fix or simply an explaination of how this can happen, so I can try to debug my setup further.

**Comment by Username404-59** [comment]
I think you should update forge, you use 36.1.3 which is ~70 versions behind the latest one

**Comment by lajxw** [comment]
Encountered the same problem,Client replicated。 
[crash-2021-07-13_20.24.05-client.txt](https://github.com/architectury/architectury-api/files/7230777/crash-2021-07-13_20.24.05-client.txt)

**Comment by shedaniel** [comment]
@lajxw your issue is unrelated and should be reported to FTBLibrary instead.

**Comment by MaxNeedsSnacks** [comment]
This is some weird race condition I still haven't figured out the exact cause of:

"Where is architectury?" only pops up if [this class](https://github.com/architectury/architectury-api/blob/1.16/forge/src/main/java/me/shedaniel/architectury/event/forge/EventHandlerImpl.java) tries to get Architectury's Mod Event Bus before it's registered, however, that should be **impossible** since we do these things in order in https://github.com/architectury/architectury-api/blob/0fcbf40c7fb93768725befee88490e8683e146fc/forge/src/main/java/me/shedaniel/architectury/forge/ArchitecturyForge.java#L31-L34, and both of these methods are synchronous so... I have no idea :/
