### ISSUE TITLE
[1.18.1] Architectury crashes on start

### ISSUE THREAD

**Issue by Vapaman** [architectury/architectury#170]
**Installed mods:**
-----------------------
Fabric loader 0.12.12
Fabric API 0.45.0
Architectury 3.3.6

Crash report:
------------------------
[crash-2021-12-30_19.03.17-client.txt](https://github.com/architectury/architectury-api/files/7793887/crash-2021-12-30_19.03.17-client.txt)

**Comment by voruti** [comment]
Can confirm.

**Comment by Juuxel** [comment]
Seems to be caused by #154.

**Comment by Atticuss320** [comment]
Happened to me too

**Comment by tacogerbil** [comment]
Same... This Crashlog references Indexed, so it may now have an incompatibility with it due to some change in Architectury-3.3.6...  Oddly enough it didn't crash my server, but it does the clients.
Reverting back to the previous version (architectury-3.3.5)of Architectury fixes the crash. 
[crash-2021-12-30_17.54.08-client.txt](https://github.com/architectury/architectury-api/files/7795126/crash-2021-12-30_17.54.08-client.txt)
.
