### ISSUE TITLE
Really unusual issue with Architectury encountered by some other devs on WK

### ISSUE THREAD

**Issue by Sunconure11** [architectury/architectury#191]
I can't seem to run into this, but others sure as shit are.

https://pastebin.com/SPPSmBzv

**Comment by Sunconure11** [comment]
https://pastebin.com/kjjPJKH5

**Comment by Sunconure11** [comment]
https://cdn.discordapp.com/attachments/868779087336984608/938539950104780851/Screenshot_from_2022-02-02_17-02-24.png

Screenshot from one of the devs

**Comment by MaxNeedsSnacks** [comment]
Can you please retry this with the new Architectury versions and Fabric Loader 0.13.x? There have been **a lot** of changes to mixins on fabric since then and I'm... kind of hopeful that it may have fixed your devs' issue as well

**Comment by MaxNeedsSnacks** [comment]
Deleted my previous comment, sorry about that I misread something in your screencap ^^'

**Comment by MaxNeedsSnacks** [comment]
I can't wrap my head around why this error would be occurring, since the only way I could possibly see that happening were to be if you downloaded an empty / corrupt jar somehow, or if the built jar we published was otherwise mucked up somehow

I've taken a look at your buildscript and you've since migrated to 1.18.2, does this still happen to some of your devs? And, this may sound really dumb, but hey tried the old reliable "nuking your gradle cache" already, considering gradle sometimes just likes to be a bit special? :P

**Comment by Sunconure11** [comment]
It no longer happens.

**Comment by MaxNeedsSnacks** [comment]
That's great to hear! A tiny theory I've had after rechecking your buildscripts was maybe that the Architectury version pulled in from Cloth Config was conflicting with the one you declared via Curse Maven, but if it doesn't happen anymore, that's good enough for me :P
