### ISSUE TITLE
Remove Optifabric Incompatibility

### ISSUE THREAD

**Issue by ghost** [architectury/architectury#226]
Optifabric has received an update to Support the latest Version of Architectuary, see https://github.com/Chocohead/OptiFabric/pull/630 so would be an idea to remove the incompatibility now, or set it for any version lower than the 1.12.11 version posted in the PR, as its working fine with Architectuary now. I altered the Json to test, works with latest edition.

**Comment by shedaniel** [comment]
Please bump this issue when the PR responsible has been merged, the optifabric incompatibility is not going to be removed unless that happens

Alternatively, you can currently use [Fabric Loader's dependency override json](https://fabricmc.net/wiki/tutorial:dependency_overrides) instead of building a custom architectury

Please note that optifine is not our list of mods we want to deal with, so "if it works it works"

**Comment by ghost** [comment]
bump as requested

**Comment by shedaniel** [comment]
I have removed the declared incompatibility for OptiFabric in Architectury, please try the new version (Might be in review on CurseForge, give it a few minutes)
