### ISSUE TITLE
Please allow access to your mods for third party lanuchers.

### ISSUE THREAD

**Issue by blackd** [architectury/architectury#262]
With the new curseforge REST API rollout your mods are currently only accessible using the curseforge site and the curseforge app.

Could you please allow access for launchers like ATLauncher.

For more info https://support.curseforge.com/en/support/solutions/articles/9000207877-project-distribution-toggle

**Comment by MisileLab** [comment]
:+1:

**Comment by MaxNeedsSnacks** [comment]
A much more likely solution is that we're going to be publishing to Modrinth, instead. Third-party _CurseForge_ launchers however, will most likely remain unsupported. We might decide to re-enable the toggle until a stable version of CurseForge for Linux that supports Minecraft is released, but not much more beyond that.

**Comment by copygirl** [comment]
Running into the same problem when our [packwiz](https://github.com/packwiz/packwiz) pack attempts to download Architectury. This just causes unnecessary headaches for users, requiring them to manually go to the mod's CurseForge page and place the .jar file into their mods folder. CurseForge for Linux is most likely not going to happen, just as it hasn't happened in the last few years. It's also a big disappointment for anyone not using the CurseForge launcher, whether its their own choice, or because they're not on Windows. Modded Minecraft is not just CurseForge and Modrinth, or just official launchers. Please reconsider.

**edit:** If the reasoning for disabling third-party downloads is Curse's reward points system, I'm willing to make the same offer as I did in https://github.com/Glitchfiend/TerraBlender/issues/72#issuecomment-1134374084 and donate 20€ to the project to offset the hypothetical loss of reward points from third-party downloads.

**another edit:** In addition, Architectury is an important, core API mod required by many others. Your choice affects any and all mods depending on yours, whether their authors themselves enable or disable third-party downloads. Therefore it doesn't just affect users, but modders as well. Your decision could cause creators to decide not to want to use your API.

**Comment by copygirl** [comment]
Someone let me know that Architectury is also available on Modrinth. While this solves the problem for me, as packwiz supports Modrinth downloads as well, the same might not be true for other tools and services out there.

**Comment by Sunconure11** [comment]
GDLauncher is working on support for Modrinth IIRC

**Comment by MaxNeedsSnacks** [comment]
From the Discord:

> OnlyIn(Dist.CLIENT) — Today at 01:07
should be mentioned
we are going to turn the toggle back on basically guaranteed
why are we not doing it right now?
first, to actually properly gauge the amount of collateral damage (and possibly look into ways of mitigating that)
second, to see whether migration to other, less blatantly anti-consumer platforms can be achieved to a certain degree
third, to try and find out what the actual "fraction" of people using 3rd party apps is
and finally, to let the storm die off a little (i'm gonna be honest, i do not want to reward people being fucking assholes with giving them what they want, which to be clear, none of you guys were and i genuinely want to thank you for that, but still)
