### ISSUE TITLE
Mod Loading Error

### ISSUE THREAD

**Issue by PinoyJason** [architectury/architectury#393]
Hello, I'd downloaded the 1.19.4 version of architectury-api for forge and when I launch to the game. There was a Mod loading error that said the mod didn't load correctly. Any clues how to fix it?

**Comment by triphora** [comment]
No logs, no screenshots, no service.

**Comment by RedstoneDubstep** [comment]
From the issue opening only recently and the problem described, I assume that the issue opener has experienced the same crash as I have. The issue is (from what I'd say) an incompatibility with the latest Forge version of Architectury and Forge 45.0.23, which seemed to have changed spawn events. Crash report is attached.
[crash-2023-03-24_16.28.51-fml.txt](https://github.com/architectury/architectury-api/files/11063906/crash-2023-03-24_16.28.51-fml.txt)

**Comment by Ashtar084** [comment]
me too the same erro i only use 3 mods wall jump and this

**Comment by dtaboadaS** [comment]
Same error, seems like some problem with the new version of Forge.

**Comment by bdlx22** [comment]
Also having the same issue.

**Comment by MaxNeedsSnacks** [comment]
Fixed in 9a6a6f2ed39586fdad638d5ca114622d596750da
