### ISSUE TITLE
[1.16.5] Seemingly random client disconnects and rare crashes

### ISSUE THREAD

**Issue by NielsPilgaard** [architectury/architectury#47]
Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/1409

Several users of Enigmatica 6 have reported a `ConcurrentModificationException` that disconnects them from servers. It seems to be random when it happens and to who, but changing difficulty to peaceful seemingly fixes it.

One user that experienced it also crashed, and the log points to Architectury: https://pastebin.com/c59HnAJT

### Versions
- Forge-1.16.5-36.0.40
- architectury-1.8.120-forge

**Comment by shedaniel** [comment]
Thanks for reporting! The crash doesn't seem to be related to the CME. The CME seems to be something modifying the nbt of the items while the packet is sending the entity equipment to the client (Which makes sense that peaceful fixes this issue, because there will not be any monsters wearing armour). I am unable to identify what mod is causing this issue unfortunately, and there is a low chance that it is architectury.

The crash below is FTB Ultimine forgetting to check whether it is connected to a server before sending a packet to the server. However, I have pushed a commit that makes this throw a better error. You will want to report this to FTB Ultimine.

https://github.com/FTBTeam/FTB-Ultimine/blob/28a59b55689983a8df7df586df787ec4f6b00634/common/src/main/java/com/feed_the_beast/mods/ftbultimine/client/FTBUltimineClient.java#L225

**Comment by NielsPilgaard** [comment]
Cool, thanks!
