### ISSUE TITLE
I've downloaded architectury but when i open MC it states that it is not installed

### ISSUE THREAD

**Issue by renehaze** [architectury/architectury#553]
I've made sure that it's not the fabric version, not sure why im having this issue

**Comment by jupiter-august** [comment]
I am also having the exact same issue on Neoforge (which I have updated to the most recent version of and I know for sure I have the most up to date java installed on my computer)
I am trying to run it in the neoforge modpack "AlltheMods10"

**Comment by jupiter-august** [comment]
> I am also having the exact same issue on Neoforge (which I have updated to the most recent version of and I know for sure I have the most up to date java installed on my computer) I am trying to run it in the neoforge modpack "AlltheMods10"
I almost forgot! Here is my crash log and normal log files! Hope it helps!

[crash-2024-09-09_01.24.55-client.txt](https://github.com/user-attachments/files/16925813/crash-2024-09-09_01.24.55-client.txt)
[latest.log](https://github.com/user-attachments/files/16925816/latest.log)

**Comment by SirTwsted** [comment]
I can verify this is happening.
I also tried using a previous version v3.0.5, but when I do that, it breaks ALL the FTB mods and demands I use v3.0.6 of Architectury, which sucks because I can't even go back until the mod is fixed by the dev.  🤷‍♀️

![Architectury API says it's not installed when it actually is installed](https://github.com/user-attachments/assets/04d6897a-ee46-4025-b784-fe12e025806d)

😳

**Comment by Jab125** [comment]
See #528 (duplicate)
